import 'tasks/clean.rake'
import 'tasks/chef.rake'
import 'tasks/chef/node/image.rake'
import 'tasks/chef/role/image.rake'
import 'tasks/cluster.rake'
import 'tasks/configuration.rake'
import 'tasks/local_gems.rake'
import 'tasks/fog/compute.rake'
import 'tasks/fog/flavors.rake'
import 'tasks/fog/images.rake'
import 'tasks/fog/security_groups.rake'
import 'tasks/fog/ssh_key.rake'
import 'tasks/fog/vms.rake'
import 'tasks/utilities.rake'

